### ISSUE TITLE
Create SRE Challenge 0 as an extension

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/create-eth-extensions#23]
Having challenges as extensions would help to maintain them, so I think we can make a try with Challenge 0, test it, and see how we feel about it.

We'd need to migrate the challenge to Foundry also, and have both options in the CLI. Separate PRs?

**Idea for a future iteration**
Install from a specific version (users could copy&paste the install link). E.g. `npx create-eth@1.0 -e challenge` (to avoid breaking the challenges on SE-2 updates)

**Comment by carletex** [comment]
Specifying a version on npx should work out of the box `npx create-eth@0.0.50`
