### ISSUE TITLE
Ponder extension

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/create-eth-extensions#7]
We already have [The Graph](https://github.com/scaffold-eth/create-eth-extensions/tree/subgraph) as curated extension, would it make sense to have also Ponder as an alternative for those that want a more minimal approach for their indexing needs?

**Comment by damianmarti** [comment]
Yeees! I can build it!

**Comment by carletex** [comment]
Great @damianmarti !!

Some ideas:

1. We can use a well-known contract as an example (a good default schema + config with comments)
2. Docker to test locally with postgres
3. Index only the latest X blocks (as default). if not, if 1 it's a popular example it'll crush the indexer with requests haha


Damu, feel free to open a draft PR and we can keep discussing there!

Thanks!!

**Comment by damianmarti** [comment]
> Great @damianmarti !!
> 
> Some ideas:
> 
> 1. We can use a well-known contract as an example (a good default schema + config with comments)

My idea is to set up Ponder to use the network config from scaffoldConfig and the ABI from the deployed contracts. I can use the simple YourContract as an example (maybe saving a log with all the greeting changes) or to be able to use another contract, I should add the contract to externalContracts (I'm not sure if it's a good idea).

> 2. Docker to test locally with postgres

I think we don't need this, running **ponder dev** (I can add this to the root package.json scripts sections). it starts a Ponder indexer using SQLite.

> 3. Index only the latest X blocks (as default). if not, if 1 it's a popular example it'll crush the indexer with requests haha
> 
> Damu, feel free to open a draft PR and we can keep discussing there!
> 
> Thanks!!

**Comment by damianmarti** [comment]
Done! https://github.com/scaffold-eth/create-eth-extensions/pull/12
