### ISSUE TITLE
OnchainKit extension

### ISSUE THREAD

**Issue by Pabl0cks** [scaffold-eth/create-eth-extensions#8]
I think it would be awesome to have an OnchainKit extension to make use of all the components and utilities they are building. 

Wonder if [Connect Account](https://onchainkit.xyz/wallet/connect-account) feature would overlap with #6. The only problem I see is OnchainKit is very active right now, would probably require important efforts to keep this extension up to date with the new features and bug fixes.

**Comment by technophile-04** [comment]
Completed in #11
